// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'community_controller_test.dart' as community_controller_test;
import 'widget_test.dart' as widget_test;

void main() {
  community_controller_test.main();
  widget_test.main();
}
